[package]
name = "bad3d"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]

[dependencies]
more-asserts = "0.2"
log = "0.4"

[dev-dependencies]
rand = "0.4"
glium = "0.22.0"
failure = "0.1"
imgui = "0.0.21"
imgui-glium-renderer = "0.0.21"

[patch.crates-io]
glium = { git = "https://github.com/thomcc/glium", branch = "glutin-0.19.0" }
