[package]
name = "t3m"
version = "0.1.0"
authors = ["Thom Chiovoloni <chiovolonit@gmail.com>"]
edition = "2018"

[dependencies]
chek = "0.1.0"
almost = "0.2.0"
cfg-if = "0.1.9"

[dev-dependencies]
quickcheck = "0.8.5"

